### ISSUE TITLE
Divide and combine

### ISSUE THREAD

**Issue by mrocklin** [jcrist/crick#1]
I would like to add a fraction of one TDigest to another.  Part of this I can do with `merge`, but I would also like the ability to attenuate all of the values by some fixed factor.  My application here is that I want to construct a hierarchy of digests for different time windows. For example I might have a digest for the last second, last five seconds, last minute, forever, etc..  Every second I might divide the one-second digest in half and add it to the five second digest.  In this way I can smoothly evolve this hierarchy of digests and get a good picture of what's happening across time as well.

**Comment by mrocklin** [comment]
I would like to make the shift method here smoother: https://github.com/dask/distributed/pull/738/files#diff-2762f279ab0adf89e52879da31baa358

**Comment by jcrist** [comment]
That's doable. I'd probably add a method `scale(factor)`, and overload `__mul__` to call it. Then your call would be `t.merge(0.5 * t2)`. This would require moving the weights to a float/double instead of an integer, or truncating (which I'd be against). Using a float shouldn't be a big deal unless we get very large weights (unlikely) - would need to hit `2**24 + 1` (or `2**53 + 1` for a double) before we'd see an error.
